### ISSUE TITLE
Sunricher ZG9101SAC-HP

### ISSUE THREAD

**Issue by SelfDestructor** [easyhomesrc/homey_easylighting#1]
Hi! Is this the GitHub page for https://homey.app/no-no/app/com.easyhome.mw.zigbee/EasyHome/ ? The URLs for the support on the app page links to a 404 page.

If I have come to the right place, my Sunricher ZG9101SAC-HP is not being detected by the EasyHome app anymore after updating to the 5.0 version of Homey. It only detects as a basic Zigbee device and will only support on/off and not dimming.

**Comment by easyhomesrc** [comment]
Hi @SelfDestructor ,

Before Homey officially releases v5.0, we cannot release v5.0 apps. This is an App that will support v5.0, which should be able to support your device. If not, please provide detailed information about the device.

https://homey.app/a/com.easyhome.easylighting/test/


Best regards.

**Comment by SelfDestructor** [comment]
Thank you so much! The app works perfectly! 😄
