### ISSUE TITLE
Add button map for ZGRC-KEY-009

### ISSUE THREAD

**Issue by RwMkrs** [easyhomesrc/homey_easylighting#10]
HI  @maginawin,

Is there a possibility to add a keymap for ZGRC-KEY-009.

I found a sample of this keymap for deconz https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3397 and https://www.zigbee2mqtt.io/devices/50208693.html for Zigbee2MQTT. 

In the Netherlands we can buy the device here https://www.leddirect.nl/yphix-draadloze-wandbediening-rgbw-zigbee-1-zone.

I can support you with testing. I've some experience in IT but not really much with github and Homey development. Probably I can contibute next time to the community with development too. 

Kind regards

**Comment by maginawin** [comment]
Hi @RwMkrs ,

Okay, no problem, there's going to be an update in two weeks.

**Comment by RwMkrs** [comment]
Thnx for the reply @maginawin. If I can support you let me know!

**Comment by maginawin** [comment]
Hi @RwMkrs ,

Here is a preview App, please have a test. https://homey.app/a/com.easyhome.easylighting/test/

**Comment by RwMkrs** [comment]
Hi @maginawin I did some tests. I checked all the the buttons and all button functions look to work as expected. I tested with multiple devices. 

The only thing I discovered is that there are some missing translations for Dutch. If you prefer I can supply these translations to you. Pleae let me know. 

Thanks in advance for the good work!
