### ISSUE TITLE
2-gang Switch doesn't work

### ISSUE THREAD

**Issue by Benklint2** [easyhomesrc/homey_easylighting#15]
I just tried using this app to get the SR-ZG9101SAC-HP-SWITCH-2CH from Sunricher to work but sadly it doesn't (it is just added as the generic ZigBee device which only lets you control one of the lights (and doesn't update the state if switch using the push button.

Here is a link to Sunrichers website for the Switch:
https://www.sunricher.com/zigbee-ac-2-gang-in-wall-switch-sr-zg9101sac-hp-switch-2ch.html

The exact relay I am using is the one from m.nu (https://www.m.nu/rela-zigbee/inbyggnadsrela-ac-2-kanaler-zigbee-sunricher) and it looks like this:
![Screenshot_2022-02-14-17-27-26-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/24275227/153904846-f62355cd-100e-4b33-8460-4b8a5697bc17.jpg)

When I try to add it it adds as a Basic Zigbee Device and under advanced it looks like this:
![Screenshot_2022-02-14-17-13-34-01_4bbfc4a7dd885a2bb189f300112a7ed4](https://user-images.githubusercontent.com/24275227/153904873-c92f585a-aca0-4baa-8e22-bb54bac85980.jpg)

They are possible to add to Philips Hue and there they show up as two different lights where one has this info:
![Screenshot_2022-02-14-17-35-39-75_37aa7df8076ee809f409ba29e0d01da1](https://user-images.githubusercontent.com/24275227/153906338-7ca965b2-66e1-48f1-a626-f75dd751390e.jpg)

And the other one this info:
![Screenshot_2022-02-14-17-35-31-71_37aa7df8076ee809f409ba29e0d01da1](https://user-images.githubusercontent.com/24275227/153906399-205d6ed7-b4b8-4731-9edb-abb0292f086d.jpg)

Many thanks in advance (I have used this app for other switches and dimmers from Sunricher and Nordtronic flawlessly). It is a rather new product from Sunricher if I understand correctly.

**Comment by maginawin** [comment]
Hi @Benklint2 ,

Thanks for your feedback, I'll update the App ASAP.

**Comment by Benklint2** [comment]
Hi @maginawin,
Many thanks for the quick reply!
Let me know if you need more info or for me to test anything.

**Comment by maginawin** [comment]
Hi @Benklint2 ,

I have updated the App, please have a test. You need to re-add your device.

https://homey.app/a/com.easyhome.easylighting/test/

**Comment by Benklint2** [comment]
I have now tried it and it works beautifully.
Many thanks for the super quick update!
