### ISSUE TITLE
Support for srp-zg9105

### ISSUE THREAD

**Issue by JohanBendz** [easyhomesrc/homey_easylighting#2]
Hi, please add support for: srp-zg9105
https://www.sunricher.com/catalogsearch/result/?q=zg9105

**Comment by maginawin** [comment]
Hi @JohanBendz ,

Can you provide me with the Product Id of one of the devices for reference?

**Comment by JohanBendz** [comment]
Manufacturer ID: Sunricher
Product ID: DIM Lighting

I do not have an interview as the user with the device that I help is still on firmware 4.2

**Comment by maginawin** [comment]
Hi @JohanBendz 

This App can only be used on Homey v5.0+, this device is already supported.

**Comment by JohanBendz** [comment]
Ah, I now see it is. Sorry, my bad 👍
