### ISSUE TITLE
Dimmer

### ISSUE THREAD

**Issue by Tennung** [easyhomesrc/homey_easylighting#4]
Hi
Sunricher 
HK-LN-DIM-A

Links in as an unknown ZigBee unit
It's a three wire dimmer

**Comment by maginawin** [comment]
Hi @Tennung ,

Did you install EasyLighting App v1.0.1 first and then add devices? If not, remove the device and add the device again.

**Comment by Tennung** [comment]
I have the Easyhome app v 1.0.34, will try the Easylighting app later today. Hopefully this will fix it :-)

**Comment by Tennung** [comment]
Worked perfect! Sorry for noobing 😁
