### ISSUE TITLE
SR-ZV9040-S Micro Smart Dimmer

### ISSUE THREAD

**Issue by geurti64** [easyhomesrc/homey_easylighting#7]
Hi,
Since March I have two Z-Wave dimmers and some Zigbee dimmers. About two weeks ago suddenly a device lost connection to my Homey and I discovered that the Sunricher dimmer lost connection as well.
I tried to include the dimmer again but only step 1 was visible. After triple push reset button I got a message something went wrong. Strange thing to me is that I could see an unknown device in Developer. Also there I could remove it. I tried several things but nothing worked.
Then suddenly I remembered the second dimmer in my storage.
I tried to include that one, but got the same results.
So, things I tried were:
- Homey PtP;
- Factory reset dimmer;
- Including by triple push reset button;
- Including by power on;
- Including near Homey (10 cm);
- Two dimmers, same result;
- Asked on Slack for help, no result on Dutch side.
Is there something you can do for me?

Edit:
Homey version 7.0.1

**Comment by easyhomesrc** [comment]
Hi @geurti64 ,

What's your Home Gateway version? I suggest you upgrade it to 7.0.1 and try again.

**Comment by geurti64** [comment]
> Hi @geurti64 ,
> 
> What's your Home Gateway version? I suggest you upgrade it to 7.0.1 and try again.

Hi,
My Homey version is 7.0.1

**Comment by geurti64** [comment]
> Hi @geurti64 ,
> 
> What's your Home Gateway version? I suggest you upgrade it to 7.0.1 and try again.

Hi,
My Homey version is 7.0.1

**Comment by easyhomesrc** [comment]
Hi @geurti64 ,

I've updated the App, please test it.

https://homey.app/a/com.easyhome.easylighting/test/

**Comment by geurti64** [comment]
> Hi @geurti64 ,
> 
> I've updated the App, please test it.
> 
> https://homey.app/a/com.easyhome.easylighting/test/

I'll test it tonight.
Thanks in advance.

**Comment by geurti64** [comment]
> Hi @geurti64 ,
> 
> I've updated the App, please test it.
> 
> https://homey.app/a/com.easyhome.easylighting/test/

I'll test it tonight.
Thanks in advance.

And meanwhile I tested it.
Seems like the first dimmer had the same issue.
The spare dimmer could get connected, double ✅
Pity thing is that for the rest works nothing but power measuring, means I can't turn off the light nor dim the light.

**Comment by easyhomesrc** [comment]
Hi @geurti64 ,

If the pairing is not successful, press and hold down the reset button for over 10 seconds, then try again. NOTE: Wait 10 seconds after each pairing operation. 

Please provide me with the following device information. I tested my device and it works.

![IMG_87F97975510B-1](https://user-images.githubusercontent.com/50604690/125718974-484c6175-b4dd-4d9a-b817-3618c70aff86.jpeg)

**Comment by geurti64** [comment]
> Hi @geurti64 ,
> 
> If the pairing is not successful, press and hold down the reset button for over 10 seconds, then try again. NOTE: Wait 10 seconds after each pairing operation.
> 
> Please provide me with the following device information. I tested my device and it works.
> 
> ![IMG_87F97975510B-1](https://user-images.githubusercontent.com/50604690/125718974-484c6175-b4dd-4d9a-b817-3618c70aff86.jpeg)

Actually that's what I did already.
I tried it again and again I get "Something went wrong".
![D2A44F99-0507-4CEE-ADC7-1FBABDD9FE85](https://user-images.githubusercontent.com/44948016/125825825-e14c2106-8efc-42e5-84c2-857bc3362a28.png)

Edit: Means I can't provide you the device information.

**Comment by easyhomesrc** [comment]
Hi @geurti64 ,

I have applied for the same device for testing, I'll get back to you after the test.

**Comment by easyhomesrc** [comment]
Hi @geurti64 ,

I contacted the manufacturer to find out that the device made about a year ago would have this problem, upgrading the Homey App won't solve this problem.

**Comment by geurti64** [comment]
Hi,
Can I open this topic again or should I start a new one?
I've issues with the same dimmer again.
Now it's losing connection with Homey. Normally it connects with a Heat-it Smoke detector but it seems like not willing anymore. There are many other options to find it's way to Homey but it seems like the dimmer wants a straight connection. Since the distance to Homey is too far it's hard to make that work successfully.
Any idea what to do about it?
I'm running Experimental app EasyLighting up to date.
