### ISSUE TITLE
Problems with adding ZV9020A

### ISSUE THREAD

**Issue by johanstalnacke** [easyhomesrc/homey_easylighting#9]
I am unable to add the Sunricher ZV9020A to my Homey. The adding process fails with the message along the lines of "something went wrong please check the pincode". I've tried with 4 different units, they all behave the same.

**Comment by maginawin** [comment]
Hi @johanstalnacke ,

I noticed this not long ago, and I'm working with Homey engineers to solve this problem.

**Comment by maginawin** [comment]
Hi @johanstalnacke ,

The ZV9020A can be added now, please have a test.

https://homey.app/a/com.easyhome.easylighting/test/

**Comment by johanstalnacke** [comment]
Works like a charm with the new version! Many thanks!!
